name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to test with'
        required: true
        default: '3.12'
        type: choice
        options:
          - '3.10'
          - '3.11'
          - '3.12'
      test-file:
        description: 'Specific test file to run (leave empty for all)'
        required: false
        default: ''
        type: string
      verbose:
        description: 'Run tests in verbose mode'
        required: false
        default: true
        type: boolean

jobs:
  manual-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run specific test file
      if: inputs.test-file != ''
      run: |
        echo "Running specific test: ${{ inputs.test-file }}"
        pytest ${{ inputs.test-file }} \
          ${{ inputs.verbose && '-vvs' || '' }} \
          --tb=short \
          --cov=hound \
          --cov-report=term-missing
    
    - name: Run all tests
      if: inputs.test-file == ''
      run: |
        echo "Running all tests"
        pytest tests/ \
          ${{ inputs.verbose && '-vvs' || '-v' }} \
          --tb=short \
          --cov=hound \
          --cov-report=term-missing
    
    - name: Display test summary
      if: always()
      run: |
        echo "Test run completed with Python ${{ inputs.python-version }}"
        echo "Test file: ${{ inputs.test-file || 'All tests' }}"